### PR TITLE
Remove content type from POST request

### PR DESCRIPTION
**Pull request by pvdosev**
This is part 1 of the bugfix for adding new experiences, and it's the simpler part. Content-type: application/json is wrong here, since we're not sending json, but multipart form data. I initially changed it to multipart/form-data, but that was wrong! It turns out you need to add the boundary to the header, and the correct solution is to leave it off completely so react can do it properly by itself!

I will now fix it in the python application, so it reads the data properly.

### CODE REVIEW

**Comment by yalsaffar** [comment]
I had the same issue with the linter checks, just run `npx prettier --write . ` and it will modify all documents with problems. And it made no conflicts or major impact on the code.

**Comment by awilkescom** [comment]
Hey @pvdosev @yalsaffar can we check the failing linter?

**Comment by yalsaffar** [comment]
@awilkescom This should be solved with the last PR merged, as I used `npx prettier --write .` and everything should be fine now.

**Comment by pvdosev** [comment]
@yalsaffar Thanks for linting the project!

**Pull request merged**
